#ifndef GPS_MSG_HPP
#define GPS_MSG_HPP

#include <cstdint>
#include <custom_types/gps_data.hpp>

/**
 * @brief GpsMsg message structure.
 * 
 * Generated by Orocos Msg Template Generator.
 */
namespace Msg {
namespace GPS {

struct GpsMsg {
    uint64_t timestamp_ns = 0;
    int counter = 0;

    CustomTypes::GpsData gpsData{};
    
    GpsMsg() = default;
};

struct SatMsg {
    uint64_t timestamp_ns = 0;
    int counter = 0;
    CustomTypes::NavSat satData{};
    
    SatMsg() = default;
};

struct HwMsg {
    uint64_t timestamp_ns = 0;
    int counter = 0;
    CustomTypes::MonHw hwData{};
    
    HwMsg() = default;
};

} // namespace GPS
} // namespace Msg

#endif // GPS_MSG_HPP
