#ifndef GPS_MSG_HPP
#define GPS_MSG_HPP

#include <cstdint>
#include <string>

/**
 * @brief GpsMsg message structure.
 * 
 * Generated by Orocos Msg Template Generator.
 */
struct GpsMsg {
    uint64_t timestamp_ms; ///< Time in milliseconds
    int counter;           ///< Message counter or sequence number

    // Add custom fields here
    
    /**
     * @brief Default constructor
     */
    GpsMsg() : timestamp_ms(0), counter(0) {}
};

#endif // GPS_MSG_HPP
